apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app
  labels:
    app: trading-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-app
  template:
    metadata:
      labels:
        app: trading-app
    spec:
      containers:
        - name: tasksapp
          image: zivamram/trading-app:0.0.6145928352
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
