apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app
  labels:
    app: trading-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trading-app
  template:
    metadata:
      labels:
        app: trading-app
    spec:
      containers:
        - name: trading-app
          image: zivamram/trading-app:0.0.6538746946
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
