apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksapp
  labels:
    app: tasksapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksapp
  template:
    metadata:
      labels:
        app: trading-app
    spec:
      containers:
        - name: tasksapp
          image: zivamram/trading-app:0.0.6109294605
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
