apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-mongo
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.type }}
  selector:
    app: mongo
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mongo.ports | toYaml | nindent 2 -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-mongo
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: mongo
    {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongo
      {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongo.mongo.image.repository }}:{{ .Values.mongo.mongo.image.tag
          | default .Chart.AppVersion }}
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ include "mychart.fullname" . }}-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mychart.fullname" . }}-pv
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  hostPath:
    path: /tmp/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" . }}-pvc
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pvc.storageRequest | quote }}