name: CI
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A        
    - name: Deploy to minikube
      run: |
        kubectl apply -f mongo.yaml
        kubectl apply -f mongo-svc.yaml
        kubectl apply -f mongo-pv.yaml
        kubectl apply -f mongo-pvc.yaml
        kubectl apply -f tasksapp.yaml
        kubectl apply -f tasksapp-svc.yaml
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Test service URLs
      run: |
        minikube service list
        minikube service tasksapp-svc --url
        echo "------------------opening the service------------------"
        curl $(minikube service tasksapp-svc --url)
        