name: CI-testing
on:
  schedule:
    - cron: '0 8,20 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Build:
      runs-on: ubuntu-latest
      name: build example and deploy to minikube
      steps:
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
            # Optional port (defaults to 465)
          port: 465
          account: 'GitHub'
          password: ${{secrets.MAIL_PASSWORD}}
          sender: GitHub
          from: ${{secrets.MAIL_ADDRESS}}
          to: ziv.chay.amram@gmail.com
          subject: mail title.
          body: your messages.
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'
