name: CI-testing
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - trigger-ci-testing

jobs:
  Build:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      
      - name: clone application from github repo.
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'ZivAmram/mahat-project-app'
          platform: 'github'  
      - name: enter the folder.
        run: ls
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      - name: build docker image
        run: |
          docker build -t zivamram/trading-app:0.0.${{ github.run_id }} .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: zivamram
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: docker push
        run: |
         docker push zivamram/trading-app:0.0.${{ github.run_id }}

      
      - name: checkout
        uses: actions/checkout@v3

      - name: Update Deployment Manifest
        run: |
         ls 
         sed -i "s|image: zivamram/trading-app:.*|image: zivamram/trading-app:0.0.${{ github.run_id }}|" ./trading-app.yaml

      - name: Ensure the trading-app.yaml
        run: |
          cat trading-app.yaml
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      
      - name: Try the cluster !
        run: kubectl get pods -A        
      
      - name: Deploy to minikube
        run: |
          kubectl apply -f mongo.yaml
          kubectl apply -f mongo-svc.yaml
          kubectl apply -f mongo-pv.yaml
          kubectl apply -f mongo-pvc.yaml
          kubectl apply -f trading-app.yaml
          kubectl apply -f trading-app-svc.yaml
      
      - name: Take a nap
        run: sleep 30
      
      - name: Check pods
        run: |
          kubectl get pods

      - name: Test Login To App
        run: |
          docker images
          minikube service list
          kubectl get pods
          minikube service trading-app-svc --url
          echo "---------------opening the service----------------"
          curl $(minikube service trading-app-svc --url)/
          curl -X POST -d "name=TEST&email=test@gmail.com&password=test" $(minikube service trading-app-svc --url)/user/signup
          curl -X POST -d "email=test@gmail.com&password=test" $(minikube service trading-app-svc --url)/user/login
<<<<<<< HEAD
      #     curl $(minikube service tasksapp-svc --url)/tasks
 
      # - name: docker push
      #   run: |
      #     echo $(cat image_tag.txt)
      #     chmod +x increase.sh
      #     ./increase.sh
      #     docker push zivamram/tasksapp-python:latest
      #     docker tag zivamram/tasksapp-python:latest zivamram/tasksapp-python:0.0.$(cat new_image_tag.txt)
      #     docker push zivamram/tasksapp-python:0.0.$(cat new_image_tag.txt)
      #     rm image_tag.txt
      #     mv new_image_tag.txt image_tag.txt
      
      
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: current_tag
      #     path: ./image_tag.txt 
=======

          
>>>>>>> b18b71698c8d0d0508d0ddb1c954c98b86b5c9b8

      - name: push to github
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: 'main'
          commit-message: 'publish'
          force-add: 'true'
          files: trading-app.yaml
          name: Ziv
          email: my.github@email.com 
  